### 查询接口
POST {{gateway}}/content/course/list?pageNo=1&pageSize=3
Content-Type: application/json

{
  "auditStatus": "202004",
  "courseName": "java",
  "status": "203001"
}

### 分类接口
GET {{gateway}}/content/course-category/tree-nodes

http://localhost:8601/#/organization/course-list

### 新增
POST http://localhost:8080/content/course

###
GET {{gateway}}/teachplan/25/tree-nodes

POST http://localhost:8086/api/media/upload/coursefile1