### 查询接口
POST {{content}}/content/course/list?pageNo=1&pageSize=3
Content-Type: application/json

{
  "auditStatus": "202004",
  "courseName": "java",
  "status": "203001"
}

### 分类接口
GET {{content}}/content/course-category/tree-nodes

http://localhost:8601/#/organization/course-list
