##
POST {{gateway}}/media/upload/coursefile
Content-Type: multipart/form-data;boundary=TestBoundary

--TestBoundary
Content-Disposition: form-data;name="filedata";filename="02.jpg"
Content-Type: application/octet-stream

<E:/图片/huawei nava5Pro/ScreenShots/SRC_20100101_090913.jpg